name: flutter_page_indicator
description: Page indicator for flutter, with multiple build-in layouts.
version: 0.0.3
homepage: https://github.com/yinxing29/flutter_page_indicator_copy

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.3.0"
  flutter: ">=0.1.4 <3.0.0"


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
